using Store.Models.Entities.Base;

namespace Store.Models.Entities;

/// <summary>
/// Stores FIDO2 / WebAuthn Public Key credentials used for biometric authentication.
/// </summary>
public class FidoCredential : BaseEntity
{
    public int Id { get; set; }
    
    public Guid UserId { get; set; }
    
    /// <summary>Unique credential identifier generated by the authenticator.</summary>
    public byte[] CredentialId { get; set; } = null!;
    
    /// <summary>The public key used to verify signatures from this authenticator.</summary>
    public byte[] PublicKey { get; set; } = null!;
    
    /// <summary>A unique, random byte array identifying the user to the authenticator.</summary>
    public byte[] UserHandle { get; set; } = null!;
    
    /// <summary>A counter maintained by the authenticator to prevent replay attacks.</summary>
    public uint SignatureCounter { get; set; }
    
    /// <summary>Authenticator Attestation GUID (identifies the make/model of the authenticator).</summary>
    public Guid AaGuid { get; set; }
    
    /// <summary>Type of credential (e.g., 'public-key').</summary>
    public string CredType { get; set; } = string.Empty;
    
    public DateTime RegDate { get; set; }

    public User User { get; set; } = null!;
}
