using System.Text;
using Store.ControlPlane.Models;

namespace Store.ControlPlane.Services;

public class TraefikConfigWriter : ITraefikConfigWriter
{
    private readonly IWebHostEnvironment _env;
    private readonly ILogger<TraefikConfigWriter> _logger;
    private readonly string _dynamicConfigDir;

    public TraefikConfigWriter(IWebHostEnvironment env, ILogger<TraefikConfigWriter> logger)
    {
        _env = env;
        _logger = logger;
        _dynamicConfigDir = Path.Combine(_env.ContentRootPath, "traefik", "dynamic");
        Directory.CreateDirectory(_dynamicConfigDir);
    }

    public async Task WriteTenantRoutingConfigAsync(Tenant tenant, CancellationToken ct = default)
    {
        var filePath = Path.Combine(_dynamicConfigDir, $"{tenant.Slug}.yml");

        var uiHostRules = new List<string>
        {
            $"`{tenant.Slug}.store.clexan.com`"
        };

        var apiHostRules = new List<string>
        {
            $"`api.{tenant.Slug}.store.clexan.com`"
        };

        // Add verified custom domain
        if (tenant.DomainConfig?.Status == DomainStatus.Verified && !string.IsNullOrEmpty(tenant.DomainConfig.CustomDomain))
        {
            uiHostRules.Add($"`{tenant.DomainConfig.CustomDomain}`");
            apiHostRules.Add($"`api.{tenant.DomainConfig.CustomDomain}`");
        }

        // Add branch subdomain rules
        if (tenant.Branches != null)
        {
            foreach (var branch in tenant.Branches)
            {
                if (branch.DomainType == BranchDomainType.Platform)
                {
                    uiHostRules.Add($"`{branch.BranchSlug}.{tenant.Slug}.store.clexan.com`");
                }
                else if (branch.DomainType == BranchDomainType.Custom && 
                         branch.VerificationStatus == DomainStatus.Verified && 
                         !string.IsNullOrEmpty(branch.CustomSubdomain))
                {
                    uiHostRules.Add($"`{branch.CustomSubdomain}`");
                }
            }
        }

        var uiRuleString = string.Join(" || ", uiHostRules.Select(h => $"Host({h})"));
        var apiRuleString = string.Join(" || ", apiHostRules.Select(h => $"Host({h})"));

        var yaml = new StringBuilder();
        yaml.AppendLine("## Auto-generated by Store.ControlPlane");
        yaml.AppendLine($"## Tenant: {tenant.Name} ({tenant.Slug})");
        yaml.AppendLine($"## Generated at: {DateTime.UtcNow:O}");
        yaml.AppendLine();
        yaml.AppendLine("http:");
        yaml.AppendLine("  routers:");
        
        // UI Router
        yaml.AppendLine($"    {tenant.Slug}-ui:");
        yaml.AppendLine($"      rule: \"{uiRuleString}\"");
        yaml.AppendLine($"      service: \"{tenant.Slug}-ui\"");
        yaml.AppendLine("      entryPoints:");
        yaml.AppendLine("        - \"websecure\"");
        yaml.AppendLine("      tls:");
        yaml.AppendLine("        certResolver: \"letsencrypt\"");
        yaml.AppendLine();

        // API Router
        yaml.AppendLine($"    {tenant.Slug}-api:");
        yaml.AppendLine($"      rule: \"{apiRuleString}\"");
        yaml.AppendLine($"      service: \"{tenant.Slug}-api\"");
        yaml.AppendLine("      entryPoints:");
        yaml.AppendLine("        - \"websecure\"");
        yaml.AppendLine("      tls:");
        yaml.AppendLine("        certResolver: \"letsencrypt\"");
        yaml.AppendLine();

        // Services
        yaml.AppendLine("  services:");
        yaml.AppendLine($"    {tenant.Slug}-ui:");
        yaml.AppendLine("      loadBalancer:");
        yaml.AppendLine("        servers:");
        yaml.AppendLine($"          - url: \"http://{tenant.Slug}-ui:8080\"");
        yaml.AppendLine();
        yaml.AppendLine($"    {tenant.Slug}-api:");
        yaml.AppendLine("      loadBalancer:");
        yaml.AppendLine("        servers:");
        yaml.AppendLine($"          - url: \"http://{tenant.Slug}-api:8080\"");

        // Atomic file write via temp file
        var tempFile = Path.GetTempFileName();
        await File.WriteAllTextAsync(tempFile, yaml.ToString(), Encoding.UTF8, ct);
        File.Move(tempFile, filePath, overwrite: true);

        _logger.LogInformation("Wrote Traefik dynamic routing configuration for {Slug} to {Path}", tenant.Slug, filePath);
    }

    public Task RemoveTenantRoutingConfigAsync(string slug, CancellationToken ct = default)
    {
        var filePath = Path.Combine(_dynamicConfigDir, $"{slug}.yml");
        if (File.Exists(filePath))
        {
            File.Delete(filePath);
            _logger.LogInformation("Removed Traefik dynamic routing configuration for {Slug}", slug);
        }
        return Task.CompletedTask;
    }
}
