using System.Text;
using Store.ControlPlane.Models;

namespace Store.ControlPlane.Services;

public class TraefikConfigWriter : ITraefikConfigWriter
{
    private readonly IWebHostEnvironment _env;
    private readonly IConfiguration _config;
    private readonly ILogger<TraefikConfigWriter> _logger;
    private readonly string _dynamicConfigDir;

    public TraefikConfigWriter(IWebHostEnvironment env, IConfiguration config, ILogger<TraefikConfigWriter> logger)
    {
        _env = env;
        _config = config;
        _logger = logger;
        _dynamicConfigDir = Path.Combine(_env.ContentRootPath, "traefik", "dynamic");
        Directory.CreateDirectory(_dynamicConfigDir);
    }

    public async Task WriteTenantRoutingConfigAsync(Tenant tenant, CancellationToken ct = default)
    {
        var filePath = Path.Combine(_dynamicConfigDir, $"{tenant.Slug}.yml");
        var rootDomain = _config["ControlPlane:RootDomain"] ?? "store.clexan.com";
        var isLocal = rootDomain.Contains("127.0.0.1") || rootDomain.Contains("localhost");

        var uiHostRules = new List<string>
        {
            $"`{tenant.Slug}.{rootDomain}`"
        };

        var apiHostRules = new List<string>
        {
            $"`api.{tenant.Slug}.{rootDomain}`"
        };

        // Add verified custom domain
        if (tenant.DomainConfig?.Status == DomainStatus.Verified && !string.IsNullOrEmpty(tenant.DomainConfig.CustomDomain))
        {
            uiHostRules.Add($"`{tenant.DomainConfig.CustomDomain}`");
            apiHostRules.Add($"`api.{tenant.DomainConfig.CustomDomain}`");
        }

        // Add branch subdomain rules
        if (tenant.Branches != null)
        {
            foreach (var branch in tenant.Branches)
            {
                if (branch.DomainType == BranchDomainType.Platform)
                {
                    uiHostRules.Add($"`{branch.BranchSlug}.{tenant.Slug}.{rootDomain}`");
                }
                else if (branch.DomainType == BranchDomainType.Custom && 
                         branch.VerificationStatus == DomainStatus.Verified && 
                         !string.IsNullOrEmpty(branch.CustomSubdomain))
                {
                    uiHostRules.Add($"`{branch.CustomSubdomain}`");
                }
            }
        }

        var uiRuleString = string.Join(" || ", uiHostRules.Select(h => $"Host({h})"));
        var apiRuleString = string.Join(" || ", apiHostRules.Select(h => $"Host({h})"));

        var yaml = new StringBuilder();
        yaml.AppendLine("## Auto-generated by Store.ControlPlane");
        yaml.AppendLine($"## Tenant: {tenant.Name} ({tenant.Slug})");
        yaml.AppendLine($"## Generated at: {DateTime.UtcNow:O}");
        yaml.AppendLine();
        yaml.AppendLine("http:");
        yaml.AppendLine("  routers:");
        
        // UI Router
        yaml.AppendLine($"    {tenant.Slug}-ui:");
        yaml.AppendLine($"      rule: \"{uiRuleString}\"");
        yaml.AppendLine($"      service: \"{tenant.Slug}-ui\"");
        yaml.AppendLine("      entryPoints:");
        yaml.AppendLine("        - \"web\"");
        yaml.AppendLine("        - \"websecure\"");
        if (!isLocal)
        {
            yaml.AppendLine("      tls:");
            yaml.AppendLine("        certResolver: \"letsencrypt\"");
        }
        yaml.AppendLine();

        // API Router
        yaml.AppendLine($"    {tenant.Slug}-api:");
        yaml.AppendLine($"      rule: \"{apiRuleString}\"");
        yaml.AppendLine($"      service: \"{tenant.Slug}-api\"");
        yaml.AppendLine("      entryPoints:");
        yaml.AppendLine("        - \"web\"");
        yaml.AppendLine("        - \"websecure\"");
        if (!isLocal)
        {
            yaml.AppendLine("      tls:");
            yaml.AppendLine("        certResolver: \"letsencrypt\"");
        }
        yaml.AppendLine();

        // Services
        yaml.AppendLine("  services:");
        yaml.AppendLine($"    {tenant.Slug}-ui:");
        yaml.AppendLine("      loadBalancer:");
        yaml.AppendLine("        servers:");
        yaml.AppendLine($"          - url: \"http://{tenant.Slug}-ui:8080\"");
        yaml.AppendLine();
        yaml.AppendLine($"    {tenant.Slug}-api:");
        yaml.AppendLine("      loadBalancer:");
        yaml.AppendLine("        servers:");
        yaml.AppendLine($"          - url: \"http://{tenant.Slug}-api:8080\"");

        // Write dynamic Traefik file
        await File.WriteAllTextAsync(filePath, yaml.ToString(), Encoding.UTF8, ct);
        _logger.LogInformation("Wrote Traefik dynamic routing configuration for {Slug} to {Path}", tenant.Slug, filePath);

        await ReloadTraefikIfLocalAsync(ct);
    }

    public async Task RemoveTenantRoutingConfigAsync(string slug, CancellationToken ct = default)
    {
        var filePath = Path.Combine(_dynamicConfigDir, $"{slug}.yml");
        if (File.Exists(filePath))
        {
            File.Delete(filePath);
            _logger.LogInformation("Removed Traefik dynamic routing configuration for {Slug}", slug);
            await ReloadTraefikIfLocalAsync(ct);
        }
    }

    private async Task ReloadTraefikIfLocalAsync(CancellationToken ct)
    {
        try
        {
            var psi = new System.Diagnostics.ProcessStartInfo
            {
                FileName = "docker",
                Arguments = "restart traefik-local",
                RedirectStandardOutput = true,
                RedirectStandardError = true,
                UseShellExecute = false,
                CreateNoWindow = true
            };
            using var proc = System.Diagnostics.Process.Start(psi);
            if (proc != null)
            {
                await proc.WaitForExitAsync(ct);
            }
        }
        catch (Exception ex)
        {
            _logger.LogDebug(ex, "Failed to reload local traefik container (may not be running or on VPS)");
        }
    }
}
