using Microsoft.EntityFrameworkCore;
using Store.DbServices.Context;
using Store.Models.Entities;
using Store.Models.Interfaces.Services;
using Microsoft.Extensions.Logging;

namespace Store.DbServices.Services;

public class ProcurementAutomationService : IProcurementAutomationService
{
    private readonly StoreDbContext _context;
    private readonly ILogger<ProcurementAutomationService> _logger;

    public ProcurementAutomationService(StoreDbContext context, ILogger<ProcurementAutomationService> logger)
    {
        _context = context;
        _logger = logger;
    }

    public async Task<int> EvaluateInventoryThresholdsAsync(CancellationToken cancellationToken = default)
    {
        _logger.LogInformation("Starting automated procurement threshold evaluation.");

        // Find all BranchItemStocks that are below their ReorderLevel
        var lowStocks = await _context.BranchItemStocks
            .Include(b => b.Item)
            .Where(b => b.ReorderLevel.HasValue && b.InStock <= b.ReorderLevel.Value && b.Item.IsActive)
            .ToListAsync(cancellationToken);

        if (!lowStocks.Any())
        {
            _logger.LogInformation("No items are below their reorder thresholds.");
            return 0;
        }

        // Group by PreferredSupplierId
        var supplierGroups = lowStocks
            .Where(s => s.Item.PreferredSupplierId.HasValue)
            .GroupBy(s => s.Item.PreferredSupplierId.Value)
            .ToList();

        int poCount = 0;

        foreach (var group in supplierGroups)
        {
            var supplierId = group.Key;
            
            // Create a new Draft PO for each supplier
            var po = new PurchaseOrder
            {
                SupplierId = supplierId,
                Status = Store.Models.Enums.PurchaseOrderStatus.Draft,
                DateCreated = DateTime.UtcNow,
                ExpectedDeliveryDate = DateTime.UtcNow.AddDays(group.Max(g => g.LeadTimeDays ?? 7)),
                Notes = "Automatically generated by Procurement Automation Engine",
                // Provide a placeholder RequestedByUserId or query an admin ID. Using Guid.Empty for system.
                RequestedByUserId = Guid.Empty
            };

            foreach (var stock in group)
            {
                var orderQty = stock.ReorderQuantity ?? (stock.ReorderLevel!.Value * 2); // default logic if null
                
                var poItem = new PurchaseOrderItem
                {
                    ItemId = stock.ItemId,
                    OrderedQuantity = orderQty,
                    UnitCost = stock.CustomCostPrice ?? stock.Item.CostPrice ?? 0
                };
                
                po.Items.Add(poItem);
            }

            _context.PurchaseOrders.Add(po);
            poCount++;
        }

        if (poCount > 0)
        {
            await _context.SaveChangesAsync(cancellationToken);
            _logger.LogInformation($"Successfully generated {poCount} automated Purchase Orders.");
        }

        return poCount;
    }
}
